### ISSUE TITLE
Need help to reproduce Figure 1 in Seon & Kim (2020) 

### ISSUE THREAD

**Issue by Huang-CL** [seoncafe/LaRT#2]
I'm attempting to reproduce Figure 1 in Seon & Kim (2020) to examine my own Lya radiative transfer code.  However, I have difficulty reproducing the analytic approximation in your figure 1.  The peak intensities I got are slightly higher compared to the red curve in your figure.  For example, in the case of T=10K, tau = 10^5, the peak value of J(x) I got is 4.8E-3.  In your plot, the peak value is about 3.9E-3.

I attached the python script I used to draw the Neufeld function below.  The result I get with this function is identical to the formula presented by Harrington 1973.  I can also reproduce Fig. 2 in Harrington 1973 using this function.  Could you guide me on how to reproduce the functions in your Figure 1? Thanks. 

```
def Ffun (w, y):
  r = complex(y,w)
  rs = complex(y,-w)
  return -np.sqrt(6)/(16*np.pi**2)*(np.log(1-np.exp(-np.pi*r))+np.log(1-np.exp(-np.pi*rs)))

def Neufeld (tau, tau_s, x):
  sigma = np.sqrt(2/3)*np.pi*x**3/(3*a)
  taup = tau*(1-2*np.pi*x**2/(3*B*a))
  return Ffun((taup-tau_s)/(2*B), np.fabs(sigma)/(2*B)) - Ffun((2*B-taup-tau_s)/(2*B), np.fabs(sigma)/(2*B))
```

**Comment by seoncafe** [comment]
Hi, Chenliang,

Please note that tau0 in my paper is not the same as tau in Neufeld (or B in Harrington). They are related to each other by tau_Neufeld = sqrt(pi) tau0. Please take a look at Equation (7) in Seon & Kim (2020). I hope this answers your question.

**Comment by Huang-CL** [comment]
Hello Prof. Seon,

Thank you so much for your fast response! It is super helpful. I indeed messed up the definition of tau.

Best,
Chenliang
